using System;
using GrantTrack.Domain.Entities;
using GrantTrack.Dto.RecommendationDto;
using GrantTrack.Dto.ReviewDtos;
using GrantTrack.Repository.RecommendationRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GrantTrack.Service.RecommendationService;

public class RecommendationService : IRecommendationService
{
    private readonly IRecommendationRepository _repo;

    public RecommendationService(IRecommendationRepository repo)
    {
        _repo = repo;
    }

    public async Task<bool> SubmitReviewAsync(int currentReviewerId, RecommendationRequestDto dto)
    {
        // Validate ApplicationId
        var appExists = await _repo.ApplicationExistsAsync(dto.ApplicationId);
        if (!appExists)
        {
            throw new ArgumentException($"Application ID {dto.ApplicationId} does not exist.");
        }

        // Validate ReviewerId
        var reviewerExists = await _repo.ReviewerExistsAsync(dto.ReviewerId);
        if (!reviewerExists)
        {
            throw new ArgumentException($"Reviewer ID {dto.ReviewerId} does not exist.");
        }

        // Security check
        if (dto.ReviewerId != currentReviewerId)
        {
            throw new InvalidOperationException("Access denied: You are not authorized to submit this recommendation.");
        }

        // Prevent re-submission (check by ApplicationId + ReviewerId)
        var existingRecommendation = await _repo.GetRecommendationByApplicationAndReviewerAsync(dto.ApplicationId, dto.ReviewerId);
        if (existingRecommendation != null)
        {
            throw new InvalidOperationException("Recommendation already submitted. You cannot update it again.");
        }

        // Create new review (ReviewId auto-generated by EF)
        var review = new Review
        {
            ApplicationId = dto.ApplicationId,
            ReviewerId = dto.ReviewerId,
            Score = dto.Score,
            Comments = dto.Comments,
            Date = DateTime.UtcNow
        };

        return await _repo.SubmitReviewAndRecommendationAsync(review, dto);
    }

}